apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: get-a-hive  # 标签匹配 ???for 
  replicas: 1
  template:
    metadata:
      labels:
        app: get-a-hive # 定义标签 之后的service要用

    spec:
       containers:
         - name: get-a-hive
           image: clairedupuich9/getahive:latest
           resources:  
            requests:    
                cpu: 100m
                memory: 50Mi
            limits:    
                cpu: 300m
                memory: 500Mi
           ports:
            - containerPort: 80
        
          